"""Initial migration

Revision ID: 5006ad3cbc96
Revises: a6afabedb1c6
Create Date: 2024-07-17 02:07:22.393943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5006ad3cbc96'
down_revision = 'a6afabedb1c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('blog_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_post_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_post_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_post_user_id'))
        batch_op.drop_index(batch_op.f('ix_blog_post_timestamp'))

    op.drop_table('blog_post')
    op.drop_table('user')
    # ### end Alembic commands ###
